/*
File nay de dinh nghia cac bien su dung nhieu lan trong ung dung
*/
// Type cua cac action lay ra hoc sinh
const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST"
const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE"
const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST"
const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
const UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE"
export {
    GET_STUDENT_REQUEST,
    GET_STUDENT_SUCCESS,
    GET_STUDENT_FAILURE,
    UPDATE_STUDENT_REQUEST,
    UPDATE_STUDENT_SUCCESS,
    UPDATE_STUDENT_FAILURE,
}